Add order entry transaction line model
mavenlink/intacct-ruby pull request #25
Opened 2020-12-22 22:51 UTC by b6b

2021-01-13 00:23 UTC, matthewdeol approved these changes

2021-01-13 21:40 UTC, lhwalsh approved these changes
Really solid changes. Love improvements on the gem

2021-01-13 21:40 UTC, lhwalsh commented on lib/intacct/actions/create.rb
> +        if legacy?
good change!

2021-01-14 16:06 UTC, kcotugno commented on lib/intacct/models/sotransaction.rb
> +        update_attributes = options.blank? ? attributes : OpenStruct.new(options)
I think the name `options` is confusing since it is used to pass attributes. Maybe `attributes_override`?

2021-01-25 17:08 UTC, toyhammered commented on lib/intacct/actions/create.rb
> +        if legacy?
love it!

2021-01-25 17:11 UTC, toyhammered requested changes
Looks great, just one small refactor!

2021-01-25 17:11 UTC, toyhammered commented on lib/intacct/actions/update.rb
> +                end
Can we move these out into methods like `generate_legacy_request` and `generate_request`?

2021-02-10 22:48 UTC, toyhammered commented on lib/intacct/models/sotransaction.rb
> +      def update_xml(xml, attributes_override = {})
this method is a monster.....

2021-02-10 22:49 UTC, toyhammered approved these changes
LGTM

2021-02-11 17:23 UTC, merged